import { useState, type FormEvent } from "react";
import type { Category } from "../lib/catalog";
import type { StoreLink } from "../lib/api";
import { Link, navigate } from "./Link";

type HeaderProps = { onCartClick: () => void; cartCount: number; categories: Category[]; storeName: string; announcement: string; navigationLinks: StoreLink[] };

export function Header({ onCartClick, cartCount, categories, storeName, announcement, navigationLinks }: HeaderProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const mobileCategories = categories.flatMap((category) => [category, ...(category.children ?? [])]);
  const submitSearch = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const query = String(new FormData(event.currentTarget).get("q") ?? "").trim();
    if (query) navigate("/shop?q=" + encodeURIComponent(query));
  };
  const links = navigationLinks.length ? navigationLinks : [{ label: "Shop", href: "/shop" }, { label: "Sale", href: "/shop?availability=sale" }, { label: "About", href: "/#about" }];

  return <><div className="bg-[#241C1E] px-4 py-2 text-center text-[10px] font-bold uppercase tracking-[0.2em] text-white">{announcement}</div><header className="border-b border-[#D8CDC6] bg-[#FBF8F3]"><div className="mx-auto flex max-w-[1180px] items-center justify-between gap-4 px-5 py-5 sm:px-8"><button className="rounded-lg p-2 text-xl text-[#241C1E] md:hidden" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen}>{menuOpen ? "×" : "☰"}</button><Link href="/" className="absolute left-1/2 -translate-x-1/2 font-serif text-2xl tracking-[0.16em] text-[#241C1E] no-underline sm:text-3xl">{storeName}</Link><nav className="hidden gap-7 text-[11px] font-bold uppercase tracking-[0.16em] md:flex" aria-label="Main navigation">{links.map((link) => <Link key={link.href + link.label} href={link.href} className="text-[#241C1E] no-underline hover:text-[#8B4D5C]">{link.label}</Link>)}</nav><div className="ml-auto flex items-center gap-3 text-sm text-[#241C1E]"><form onSubmit={submitSearch} className="hidden items-center rounded-lg border border-[#D8CDC6] bg-white sm:flex"><label htmlFor="header-search" className="sr-only">Search products</label><input id="header-search" name="q" placeholder="Search" className="h-10 w-24 bg-transparent px-3 text-xs outline-none placeholder:text-[#6E5F63]" /><button type="submit" aria-label="Search products" className="px-3 text-lg text-[#8B4D5C]">⌕</button></form><button onClick={onCartClick} className="flex min-h-10 items-center gap-2 rounded-lg px-2 font-bold hover:bg-[#F5E5E1]" aria-label={"Open bag with " + cartCount + " items"}>Bag <span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-[#8B4D5C] px-1 text-[10px] text-white">{cartCount}</span></button></div></div>{menuOpen ? <nav className="border-t border-[#D8CDC6] px-5 pb-5 pt-4 md:hidden" aria-label="Mobile navigation"><form onSubmit={submitSearch} className="mb-5 flex rounded-lg border border-[#D8CDC6] bg-white"><label htmlFor="mobile-search" className="sr-only">Search products</label><input id="mobile-search" name="q" placeholder="Search the collection" className="h-11 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" /><button type="submit" className="px-4 font-bold text-[#8B4D5C]">Search</button></form><div className="grid grid-cols-2 gap-y-3 text-sm">{links.map((link) => <Link key={link.href + link.label} href={link.href} onClick={() => setMenuOpen(false)} className="font-medium text-[#241C1E] no-underline hover:text-[#8B4D5C]">{link.label}</Link>)}</div><p className="mb-3 mt-6 text-[10px] font-bold uppercase tracking-[0.16em] text-[#6E5F63]">Browse categories</p><div className="grid grid-cols-2 gap-y-3 text-sm">{mobileCategories.map((category) => <Link key={category.slug} href={"/shop?category=" + category.slug} onClick={() => setMenuOpen(false)} className="text-[#241C1E] no-underline hover:text-[#8B4D5C]">{category.label}</Link>)}</div></nav> : null}</header></>;
}
